alias g='git'
alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gdog='git dog'
alias glog='git l'
alias glogme='glog --author="<$(git config user.email)>"'
